### ISSUE TITLE
Some characters are showing up as squares with ? inside them

### ISSUE THREAD

**Issue by diogo19** [dracula/powershell#41] opened 2020-09-02 22:06 UTC
**Description of the issue**
After installing it, everything went smooth, very beautiful color scheme, but then I got using PowerShell and some unicode(I'm guessing) characters are showing as squares with question marks inside of them

**Screenshots**
![Untitled](https://user-images.githubusercontent.com/43421345/92041778-425fdf00-ed4f-11ea-9804-739c922d1dc3.png)

**Version Information**

![Untitled2](https://user-images.githubusercontent.com/43421345/92041832-5c99bd00-ed4f-11ea-9159-b1ea57d67747.png)

**Comment by waf** [comment] 2020-09-06 07:22
Hi @diogo19, I agree it looks like a unicode problem. Are you using the Consolas font? For me, it can display:

![image](https://user-images.githubusercontent.com/97195/92320408-7edf5380-f04b-11ea-93a3-6f7171fa076f.png)

Additionally, if you go to your terminal's properties, what is the current code page setting?

![image](https://user-images.githubusercontent.com/97195/92320420-a1716c80-f04b-11ea-91fc-7599f06fd670.png)

I'm running `PowerShell 5.1.19041.1`, and don't have any special configuration that sets the above value.

If you could provide the test data / script that is giving you the ⍰ symbols, I'll try to reproduce that.

**Comment by diogo19** [comment] 2020-09-06 17:24
Hi, thanks for the reply!
My Current code page is '850 (OEM - Muntilingual Latin I)'.
The error is occuring whenever it tries to display ´ ` ç, those types of characters. The screenshot I posted earlier was from a query I did on a mongoDB via shell. And yes I'm using Consolas

**Comment by waf** [comment] 2021-01-07 15:32
Hi @diogo19, did switching to UTF-8 fix this issue? Or would you rather not do that? Thanks!

**Comment by waf** [comment] 2021-08-01 04:51
Closing this due to age; feel free to reopen.

**Closed as completed by waf** 2021-08-01 04:51 UTC
